version: "3.1"
services:
  linknau_postgres:
    image: postgres:15.1
    ports:
      - "7432:5432"
    environment:
      POSTGRES_DB: linknau
      POSTGRES_USER: the_patriot
      POSTGRES_PASSWORD: lalilulelo
    volumes:
      - linknau_db_data:/var/lib/postgresql/data

  linknau_redis:
    image: redis:6-alpine
    command: redis-server --requirepass abangj
    ports:
      - "8379:6379"

  linknau_sonarqube:
    image: mwizner/sonarqube:8.9.5-community
    profiles:
      - sonar
    environment:
      SONAR_FORCEAUTHENTICATION: "false"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "21000:9000"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_data_x86:
  sonarqube_extensions_x86:
  sonarqube_logs_x86:
  linknau_db_data:
    driver: local
